services:
  postgres:
    image: postgres:16
    container_name: postgres_financas
    restart: always
    environment:
      POSTGRES_DB: financas
      POSTGRES_USER: financas_user
      POSTGRES_PASSWORD: financas_senha
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    image: maven:3.9.6-eclipse-temurin-17
    container_name: financas_app
    working_dir: /app
    volumes: 
      - .:/app
      - ~/.m2:/root/.m2
    command: mvn spring-boot:run
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION}

volumes:
  pgdata:
