services:
  postgres:
    image: postgres:16
    container_name: postgres_financas
    restart: always
    environment:
      POSTGRES_DB: financas
      POSTGRES_USER: financas_user
      POSTGRES_PASSWORD: financas_senha
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    container_name: financas_app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    volumes:
      - ./logs:/app/logs
    env_file: .env
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION}
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/financas
      - SPRING_DATASOURCE_USERNAME=financas_user
      - SPRING_DATASOURCE_PASSWORD=financas_senha
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_FLYWAY_ENABLED=true


volumes:
  pgdata: